// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assignment.Models;

[Keyless]
public partial class Products_by_Category
{
    [Required]
    [StringLength(15)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(40)]
    public string ProductName { get; set; }

    [StringLength(20)]
    public string QuantityPerUnit { get; set; }

    public short? UnitsInStock { get; set; }

    public bool Discontinued { get; set; }
}