// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Assignment.Contexts;
using Assignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Assignment.Contexts.Configurations
{
    public partial class Products_Above_Average_PriceConfiguration : IEntityTypeConfiguration<Products_Above_Average_Price>
    {
        public void Configure(EntityTypeBuilder<Products_Above_Average_Price> entity)
        {
            entity.ToView("Products Above Average Price");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Products_Above_Average_Price> entity);
    }
}
